service: puppeteer-scraper

provider:
  environment:
    ENV: ${self:provider.stage}
  name: aws
  region: us-east-2
  runtime: nodejs20.x
  stage: ${opt:stage, "dev"}

functions:
  scraper:
    memorySize: 512
    timeout: 300
    image:
      uri: 637423352927.dkr.ecr.us-east-2.amazonaws.com/scraper:latest
      command:
        - dist/index.handler
